#+TITLE: Ant Command Line Wrapper

* Summary

This is an [[http://ant.apache.org][Apache Ant]] command line wrapper similar to the [[http://www.gradle.org/docs/current/userguide/gradle_wrapper.html][Gradle command line wrapper]].

What can you do with it?
- You can generate an Ant wrapper for a project from a machine with an existing Ant installation.
- You can share the project without requiring an existing Ant installation from the 'application builder'.

This project is a quick rip of [[https://github.com/bdemers/maven-wrapper][maven-wrapper]] adapted for Apache Ant.

The wrapper functionality is provided via a custom Apache Ant task.

* Notes
- This project was only tested with Apache Ant 1.7.0 and above, under Mac OSX, Linux and Windows.
- The tool has not been tested with very complex builds where *many classloaders* could be involved.

* Building the program
You'll need a recent Apache Ant version (Only tested with Ant 1.7.0 and above).

From the project directory, run the following command to build the jar file:

 : ant

You can also generate the Ant wrapper for the project itself!

 : ant wrapper

Once the wrapper is installed, you can play with it, as you please:
 : ./antw -projecthelp

* Installation

The build process will generate the resulting jar in the project *dist* folder.

You have 2 installation options:
- Drop the jar at the root of your existing projects or any other given location (Ant taskdef with classpath).
- Drop the jar in your *ANT_HOME/lib* folder (ant taskdef without any classpath setup).

* Usage
** Sample build script
 : <?xml version="1.0"?>
 : <project name="AntWrapperProject" default="generatewrapper">
 : <!-- The optional Ant Task also accepts a baseDistributionUrl properties for the Ant zip files binaries -->
 : <!-- if you dropped the wrapper jar in ANT_HOME/lib -->
 : <taskdef name="genAntWrapper" classname="com.rimerosolutions.buildtools.ant.wrapper.AntWrapperTask"/>
 : 	
 : 	<!-- if you have the wrapper jar at the root folder of your project 
 : 	<taskdef name="genAntWrapper" classname="com.rimerosolutions.buildtools.ant.wrapper.AntWrapperTask">
 : 	<classpath>
 : 	    <pathelement location="ant-wrapper-0.0.1-SNAPSHOT.jar"/>
 : 	  </classpath>
 :   </taskdef>
 :   --> 
 : 
 : 	<target name="generatewrapper">
 :      <genAntWrapper/>
 :     </target>
 : </project>

** Wrapper generation

With the above sample script, accordingly to the *taskdef* approach that you selected, run the following:
 : ant generatewrapper

This will create 5 main artefacts at the root of your project folder :
- *antw* : A UNIX command wrapper.
- *antw.bat* : A Windows command wrapper.
- *antw.cmd* : Environment variable helper for Windows.
- *lcp.bat* : The usual Windows classpath utility script.
- *wrapper* : A folder containing the launcher supporting files.

** Testing
- Run your current project via the Ant wrapper instead of your local Ant installation.
- Build your project with the Ant wrapper on a machine that doesn't have an existing Ant installation.
