#+TITLE: Ant Command Line Wrapper

* Summary

This is an [[http://ant.apache.org][Apache Ant]] command line wrapper similar to the [[http://www.gradle.org/docs/current/userguide/gradle_wrapper.html][Gradle command line wrapper]].

What can you do with it?
- You can generate an Ant wrapper for a project from a machine with an existing Ant installation.
- You can share the project without requiring an existing Ant installation from the 'builder'.

This project is a quick rip of [[https://github.com/bdemers/maven-wrapper][maven-wrapper]] adapted for Apache Ant.

* Notes
- This project was only tested with Apache Ant 1.7.0 and above.
- _Windows Support is TRUELY incomplete_, but present. It will be added once I get a Windows machine around to play with.

* Building the program
You'll need a recent Apache Ant version (Only tested with Ant 1.7.0 and above).

From the project directory, run the following command to build the jar file:

 : ant

You can also generate the Ant wrapper for the project itself!

 : ant wrapper

Once the wrapper is installed, you can play with it, as you please:
 : ./antw -projecthelp

* Installation

The build process will generate the resulting jar in the project *dist* folder.

You have 2 installation options:
- Drop the jar at the root of your project.
- Drop the jar in your *ANT_HOME/lib* folder.

* Usage
** Sample build script
 : <?xml version="1.0"?>
 : <project name="AntWrapperProject" default="generatewrapper">
 : <!-- if you dropped the wrapper jar in ANT_HOME/lib -->
 : <taskdef name="genAntWrapper" classname="com.rimerosolutions.buildtools.ant.wrapper.AntWrapperTask"/>
 : 	
 : 	<!-- if you have the wrapper jar at the root folder of your project 
 : 	<taskdef name="genAntWrapper" classname="com.rimerosolutions.buildtools.ant.wrapper.AntWrapperTask">
 : 	<classpath>
 : 	    <pathelement location="ant-wrapper-0.0.1-SNAPSHOT.jar"/>
 : 	  </classpath>
 :   </taskdef>
 :   --> 
 : 
 : 	<target name="generatewrapper">
 :      <genAntWrapper/>
 :     </target>
 : </project>

** Wrapper generation

With the above sample script, accordingly to the *taskdef* approach that you selected, run the following:
 : ant generatewrapper

This will create 4 main artefacts at the root of your project folder :
- *antw* : A unix command wrapper.
- *antw.bat* : A windows command wrapper (Untested, incomplete and likely not working yet).
- *lcp.bat* : The usual windows classpath utility script.
- *wrapper* : A folder containing the launcher supporting files.

** Testing
Now from another Unix/Linux machine, copy your Ant project and run your ant tasks via the *antw* wrapper!
